"""initial migration'


Revision ID: 573fec3ecc0d
Revises: 
Create Date: 2021-02-11 12:37:55.577117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573fec3ecc0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('profiles',
    sa.Column('profileid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('lname', sa.String(), nullable=False),
    sa.Column('account_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github', sa.String(), nullable=False),
    sa.Column('front_end', sa.Boolean(), nullable=False),
    sa.Column('back_end', sa.Boolean(), nullable=False),
    sa.Column('full_stack', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('profileid')
    )
    op.create_table('post',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('post_name', sa.String(), nullable=False),
    sa.Column('post_description', sa.String(), nullable=False),
    sa.Column('account_active', sa.Boolean(), nullable=False),
    sa.Column('front_end', sa.Boolean(), nullable=False),
    sa.Column('back_end', sa.Boolean(), nullable=False),
    sa.Column('full_stack', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('post_github', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profileid'], ),
    sa.PrimaryKeyConstraint('postid')
    )
    op.create_table('profile_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profileid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('messages', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.postid'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profileid'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('profile_images')
    op.drop_table('post')
    op.drop_table('profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
