name: CI/CD
on:
  push:
    branches: [ main ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        env:
          FLASK_ENV: testing
          AWS_ACCESS_KEY_ID: 1
          AWS_SECRET_ACCESS_KEY: 1
          AWS_S3_BUCKET: 1
        run: |
          echo DB_URI=sqlite:///:memory: >> .env
          cd src
          python -m unittest discover tests/
      
